#!/bin/bash
# *******************************************************************************
# Copyright (c) 2008 International Business Machines Corp.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    Ajith Ramanath            - initial API and implementation
#    Radhakrishnan Thangamuthu - initial API and implementation
#    Mike Fulton               - initial API and implementation
# *******************************************************************************

# Generate a time line - provide label through parms, input from stdin, output to stdout
# e.g. executionTime " Compilation Test "

graph -C -m 1 -T ps -f 0.02 -l Y -X "Iteration" -Y "Time (in Nanoseconds)" -L " $* " 
