#!/bin/bash
# *******************************************************************************
# Copyright (c) 2008 International Business Machines Corp.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    Ajith Ramanath            - initial API and implementation
#    Radhakrishnan Thangamuthu - initial API and implementation
#    Mike Fulton               - initial API and implementation
# *******************************************************************************

# Generate a histogram - provide label through parms, input from stdin, output to stdout
# e.g. histogram " MemCacheTest "

graph -C -m 1 -T ps -l X -l Y -X "Time (in Nanoseconds)" -Y Distribution -L " $* " 
