/*******************************************************************************
 * Copyright (c) 2008 International Business Machines Corp.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Ajith Ramanath            - initial API and implementation
 *    Radhakrishnan Thangamuthu - initial API and implementation
 *    Mike Fulton               - initial API and implementation
 *******************************************************************************/

package com.ibm.realtime.rtmb.tools;

import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;

public class ExecutionTime extends RTMBTool {
	private PrintStream _output;

	public ExecutionTime(InputStream in, PrintStream out) {
		super(in); 
		_output = out;
	}

	/**
	 * @param Provide an input file of execution times from the 
	 * Real Time Micro Benchmark Suite, and this will generate 
	 * an execution-time file suitable for input to a plotting program like the
	 * Linux graph program.
	 */
	public static void main(String[] args) {
		if (args.length != 0) {
			System.err.println("Syntax: ExecutionTime <report-file >plot-file");
			System.err.println("  where report-file is a report generated by the C, C++ or Java Real Time Micro Benchmark suite");
			System.err.println("  and plot-file is the file to be created");
			return;
		}
		
		ExecutionTime h = new ExecutionTime(System.in, System.out);
		Double[] d = null;
		try {
			d = h.read();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		h.write(d);
	}

	private void write(Double[] data) {
		for (int i=0; i<data.length; ++i) {
			writeEntry(i, data[i]);
		}
	}

	private void writeEntry(int entry, double value) {
		String ey = Double.toString(value);
		String sy = ey;
		String sx = Integer.toString(entry);
		String ex = Integer.toString(entry+1);
		
		_output.println(sx + " " + sy + " " + 
				sx + " " + ey + " " +
				ex + " " + ey + " " +
				ex + " " + sy);
	}
}
