/*******************************************************************************
 * Copyright (c) 2008 International Business Machines Corp.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Ajith Ramanath            - initial API and implementation
 *    Radhakrishnan Thangamuthu - initial API and implementation
 *    Mike Fulton               - initial API and implementation
 *******************************************************************************/
 
package com.ibm.realtime.rtmb.params;

public class TestInfo {

	/** Name of the test as mentioned in the input file. */
	private String testName;

	/** Test description as mentioned in the input file. */
	private String testDesc;

	/** Whether this test is a configuration test or not. */
	private boolean isConfigTest;

	/** Threshold value */
	private int threshold;

	/** Number of iterations that this test needs to run. */
	private int numIterations;

	/** A score generated by some reference machine for this test */
	private double referenceScore;

	/**
	 * Constructs a new object of type TestTimes.
	 *
	 */
	public TestInfo() {
		this.referenceScore = 1;
	}

	/**
	 * Returns the name of the test.
	 * @return The name of the test.
	 */
	public String getTestName() {
		return testName;
	}

	/**
	 * Sets the name of the Bench Mark test.
	 * @param str Name of the test.
	 */

	public void setTestName (String str) {
		testName = str;
	}

	/**
	 * Sets the description of the Bench Mark test.
	 * @param str Description of the test.
	 */
	public void setTestDesc (String str) {
		testDesc = str;
	}

	public void setConfigTest(boolean value) {
		isConfigTest = value;
	}

	public boolean isConfigTest() {
		return isConfigTest;
	}

	/**
	 * Returns the description of the Bench Mark test.
	 */
	public String getTestDesc() {
		return testDesc;
	}

	/**
	 * Sets the number of iterations that this test needs to run for.
	 * @param iters Number of iterations to run the test
	 */
	public void setTestIterations (int iters) {
		numIterations = iters;
	}

	/**
	 * Returns the number of iterations that this test needs to be run.
	 */
	public int getTestIterations () {
		return numIterations;
	}

	public int getThreshold() {
		return threshold;
	}

	public void setThreshold(int threshold) {
		this.threshold = threshold;
	}

	public double getReferenceScore() {
		return referenceScore;
	}

	public void setReferenceScore(double referenceScore) {
		/*
		 * Make sure that referenceScore is always greater
		 * than 0. If it is equal to 0 or lesser, some
		 * unpredicatable results can happen.
		 */
		if (referenceScore > 0) {
			this.referenceScore = referenceScore;
		}
	}
}